### ISSUE TITLE
Requesting help with a similar project!

### ISSUE THREAD

**Issue by ghost** [Clickydude/minecraft-web-chat-client#1]
I am working on a similar project but I don't  want the user to have to use `npm` or something similar, I want to host it using the web (GitHub Pages). It's still codenamed and I don't have a good name for it yet here is the link https://github.com/MrHallway0/Project-no-ghost. You can name your own terms for me to get you to work on it I just don't think I can do it all by my self!

**Comment by ghost** [comment]
P.S. When running on Windows you get this. 

```
internal/modules/cjs/loader.js:1174
    throw err;
    ^

SyntaxError: C:\Users\dhall\minecraft-web-chat-client\minecraft.json: Unexpected token S in JSON at position 40
    at parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1171:22)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\dhall\minecraft-web-chat-client\index.js:7:17)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
```

and I haven't tried it on Linux yet...

**Comment by Clicky26** [comment]
Hi @MrHallway0 and thanks for your interest. I'd love to help out where I can with the project you've got in mind however now isn't a great time as I've got exams and a lot of studying to be doing. If you've got the odd question or something I can slowly work on then feel free to get in touch and I'll see what I can do.

I'd recommend taking a look at this project as well btw which is a lot more feature-rich and better produced than my quite barebones implementation. https://github.com/rom1504/MinecraftChat

I'd suggest having a play around with running it on Heroku because then you get the full capability of npm in a free host. I don't have any experience with Github Pages but it might be able to do all you need.

Assuming you're planning on using mineflayer then you should also hop onto the PrismarineJS Discord server https://discord.gg/GsEFRM8 where there's many people who could help you out.

Good luck!

**Comment by Clicky26** [comment]
Also regarding your error. It seems as though you haven't populated `minecraft.json` with your minecraft account details and rather left it as my defaults which is:
`{
    "host": "SERVER_ADDR",
    "port": SERVER_PORT,
    "username": "ACC_EMAIL",
    "password": "ACC_PWD",
    "version": "1.12.2"
}`

I was able to recreate the error and can confirm that it works on a fresh clone with my account details.

**Comment by ghost** [comment]
Okay, Thank you I wish you luck on your exams and I don't understand how I could have forgotten to set up `minecraft.json` I will tell you if I need any more help with it and close this.
